alpha: 3.0
batch_size: 2
cfg: unet_ce_hard_per_im_s8841_all
criterion: hard_per_im_cross_entropy
data_dir: /media/hdd1/pkao/brats2018/training
dataset: SingleData
gpu: '3'
name: unet_ce_hard_per_im_s8841_all
net: Unet
net_params:
  dropout: 0.3
  n: 16
  norm: gn
num_epochs: 300
opt: Adam
opt_params:
  amsgrad: true
  lr: 0.001
  weight_decay: 0.0001
out: ''
root: /usr/data/pkao/brats2018/
sample_size: 25
save_freq: 50
schedule:
  150: null
  250: null
seed: 8841
start_iter: 0
sub_sample_size: 19
target_size: 9
test_data_dir: /media/hdd1/pkao/brats2018/validation
test_transforms: Compose([ Pad((0, 0, 0, 5, 0)), NumpyType((np.float32, np.int64)),
  ])
train_dir: /home/pkao/BraTS2018/segmentation/ckpts
train_list: all.txt
train_transforms: Compose([ RandCrop(128), NumpyType((np.float32, np.int64)), ])
valid_freq: 50
workers: 8
